package vista;

public class Registro {

	private enum enumDisplay {CURRENT_STATE, SETTING_FORM_EDIT, SETTING_FORM_VIEW , SETTING_LIST, SCHEDULE_LIST, SCHEDULE_FORM_VIEW, REPORT_LIST, SCHEDULE_FORM_EDIT};
}

